apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: timetrkr

resources:
  - namespace.yml
  - persistent-volume.yml
  - deployment.yml
  - service.yml
  # - ingress.yml  # Uncomment if using ingress

commonLabels:
  app: timetrkr
  version: v1

images:
  - name: ghcr.io/your-username/timetrkr
    newTag: latest