apiVersion: v1
kind: PersistentVolume
metadata:
  name: timetrkr-db-pv
  labels:
    app: timetrkr
    component: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/timetrkr/db
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timetrkr-db-pvc
  namespace: default
  labels:
    app: timetrkr
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage